### ISSUE TITLE
Convenção de nomenclatura no código

### ISSUE THREAD

**Issue by fernandokm** [GrupoTuring/Aprendizado-por-Reforco#15]
Em relação ao código (i.e. nomes de funções, variáveis, ...), precisamos convencionar em qual língua esses nomes vão ser escritos (e se vai ter diferença entre variáveis e funções), porque no momento temos alguns arquivos em português e outros em inglês. Conforme discussões anteriores, uma possibilidade seria utilizar inglês pros nomes tradicionais (e.g. `env`) e português pros outros.

Caso as funções sejam nomeadas em português, tem um segundo ponto, que talvez não precise ser decidido (e possa ser deixado à preferência de cada um). Os nomes das funções devem ficar no infinitivo ou imperativo?

**Comment by Berbardo** [comment]
Prefiro inglês.

- Fica mais fácil num geral de manter e padronizar
- Por mais que português seja mais fácil pra quem não manja tanto inglês, aprendendo com código EN e explicação PT ajuda a preparar melhor essas pessoas a entenderem outras implementações, acaba dando um conhecimento mais "prático"
- Comentários no código não sei se seria melhor inglês ou português, em PT acho que ficaria mais claro num geral, mas tem o problema de padronização

**Comment by Berbardo** [comment]
Também tem o fato de que boa parte do código já vai ter que estar inevitavelmente em inglês né, por causa das funções e métodos do Python e das bibliotecas, e.g. append, fit, step, etc.

**Comment by fernandokm** [comment]
> Prefiro inglês.
> 
> * Fica mais fácil num geral de manter e padronizar

Concordo (depois de todas as discussões que já tivemos disso, acho que esse é o ponto que todos certamente concordam...)

> * Por mais que português seja mais fácil pra quem não manja tanto inglês, aprendendo com código EN e explicação PT ajuda a preparar melhor essas pessoas a entenderem outras implementações, acaba dando um conhecimento mais "prático"

Concordo que é bom se acostumar com código em inglês, mas acho bom conversarmos com os outros, porque isso esbarra com algumas das coisas que a gente costuma discutir.

> * Comentários no código não sei se seria melhor inglês ou português, em PT acho que ficaria mais claro num geral, mas tem o problema de padronização

Então, eu vejo problemas de padronização nos dois casos: comentários em PT tem problemas com o código em EN e comentários EN tem problemas com o texto PT. Acho que o caso preferível seria o comentários em português, principalmente porque eles são uma forma de texto. Acho o inglês mais justificável no código, porque o inglês de código acaba sendo mais simples. E a gente provavelmente vai acabar misturando um pouco de EN/PT nas células de texto dos notebooks (a não ser que eles sejam escritos por completo em EN)


> Também tem o fato de que boa parte do código já vai ter que estar inevitavelmente em inglês né, por causa das funções e métodos do Python e das bibliotecas, e.g. append, fit, step, etc.

Sim, concordo completamente.

**Comment by anor4k** [comment]
Invadindo pra comentar que no projeto atual de CV decidimos manter código em inglês e documentação/comentários em português, para ser mais alinhado com os objetivos em geral do grupo

**Comment by dueiras** [comment]
Eu concordo com o bernardo e prefiro o código em inglês, até porque imagino que com os comentários já seja o suficiente para entender, além do código ficar mais padrão

**Comment by fernandokm** [comment]
Decisão final: código em inglês e comentários/texto em português, pelos motivos já expostos acima.

Observação:
- Nomes de algoritmos e outras coisas do gênero (e.g. "Q-Learning" podem ser mantidos em inglês)
